In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
test1=pd.read_csv('train.csv')

In [4]:
test1.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
count        7352.000000        7352.000000        7352.000000   
mean            0.274488          -0.017695          -0.109141   
std             0.070261           0.040811           0.056635   
min            -1.000000          -1.000000          -1.000000   
25%             0.262975          -0.024863          -0.120993   
50%             0.277193          -0.017219          -0.108676   
75%             0.288461          -0.010783          -0.097794   
max             1.000000           1.000000           1.000000   

       tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
count       7352.000000       7352.000000       7352.000000       7352.000000   
mean          -0.605438         -0.510938         -0.604754         -0.630512   
std            0.448734          0.502645          0.418687          0.424073   
min           -1.000000         -0.999873         -1.000000         -1.000000   
25%           -0.992754         -0.978129         -0.980233         -0.993591   
50%           -0.946196         -0.851897         -0.859365         -0.950709   
75%           -0.242813         -0.034231         -0.262415         -0.292680   
max            1.000000          0.916238          1.000000          1.000000   

       tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X     ...       \
count       7352.000000       7352.000000       7352.000000     ...        
mean          -0.526907         -0.606150         -0.468604     ...        
std            0.485942          0.414122          0.544547     ...        
min           -1.000000         -1.000000         -1.000000     ...        
25%           -0.978162         -0.980251         -0.936219     ...        
50%           -0.857328         -0.857143         -0.881637     ...        
75%           -0.066701         -0.265671         -0.017129     ...        
max            0.967664          1.000000          1.000000     ...        

       fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
count                      7352.000000                      7352.000000   
mean                         -0.307009                        -0.625294   
std                           0.321011                         0.307584   
min                          -0.995357                        -0.999765   
25%                          -0.542602                        -0.845573   
50%                          -0.343685                        -0.711692   
75%                          -0.126979                        -0.503878   
max                           0.989538                         0.956845   

       angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
count                  7352.000000                           7352.000000   
mean                      0.008684                              0.002186   
std                       0.336787                              0.448306   
min                      -0.976580                             -1.000000   
25%                      -0.121527                             -0.289549   
50%                       0.009509                              0.008943   
75%                       0.150865                              0.292861   
max                       1.000000                              1.000000   

       angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
count                       7352.000000                           7352.000000   
mean                           0.008726                             -0.005981   
std                            0.608303                              0.477975   
min                           -1.000000                             -1.000000   
25%                           -0.482273                             -0.376341   
50%                            0.008735                             -0.000368   
75%                            0.506187                              

In [5]:
test1.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X    ...     \
0         -0.923527         -0.934724    ...      
1         -0.957686         -0.943068    ...      
2         -0.977469         -0.938692    ...      
3         -0.989302         -0.938692    ...      
4         -0.990441         -0.942469    ...      

   fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                        -0.710304                    -0.112754   
1                        -0.861499                     0.053477   
2                        -0.760104                    -0.118559   
3                        -0.482845                    -0.036788   
4                        -0.699205                     0.123320   

   angle(tBodyAccJerkMean),gravityMean)  angle(tBodyGyroMean,gravityMean)  \
0                              0.030400                         -0.464761   
1                             -0.007435                         -0.732626   
2                              0.177899                          0.100699   
3                             -0.012892                          0.640011   
4                              0.122542                          0.693578   

   angle(tBodyGyroJerkMean,gravityMean)  angle(X,gravityMean)  \
0                             -0.018446             -0.841247   
1                              0.703511             -0.844788   
2                              0.808529             -0.848933   
3                             -0.485366             -0.848649   
4                             -0.615971             -0.847865   

   angle(Y,gravityMean)  angle(Z,gravityMean)  subject  Activity  
0              0.179941             -0.058627        1  STANDING  
1              0.180289             -0.054317        1  STANDING  
2              0.180637             -0.049118        1  STANDING  
3              0.181935             -0.047663        1  STANDING  
4              0.185151             -0.043892        1  STANDING  

[5 rows x 563 columns]

In [4]:
X=test1.drop('Activity',axis=1)
y=test1['Activity']

In [15]:
test1['Activity'].value_counts()

LAYING                1407
STANDING              1374
SITTING               1286
WALKING               1226
WALKING_UPSTAIRS      1073
WALKING_DOWNSTAIRS     986
Name: Activity, dtype: int64

In [16]:
pd.get_dummies(test1['Activity'])

LAYING  SITTING  STANDING  WALKING  WALKING_DOWNSTAIRS  WALKING_UPSTAIRS
0          0        0         1        0                   0                 0
1          0        0         1        0                   0                 0
2          0        0         1        0                   0                 0
3          0        0         1        0                   0                 0
4          0        0         1        0                   0                 0
5          0        0         1        0                   0                 0
6          0        0         1        0                   0                 0
7          0        0         1        0                   0                 0
8          0        0         1        0                   0                 0
9          0        0         1        0                   0                 0
10         0        0         1        0                   0                 0
11         0        0         1        0                   0                 0
12         0        0         1        0                   0                 0
13         0        0         1        0                   0                 0
14         0        0         1        0                   0                 0
15         0        0         1        0                   0                 0
16         0        0         1        0                   0                 0
17         0        0         1        0                   0                 0
18         0        0         1        0                   0                 0
19         0        0         1        0                   0                 0
20         0        0         1        0                   0                 0
21         0        0         1        0                   0                 0
22         0        0         1        0                   0                 0
23         0        0         1        0                   0                 0
24         0        0         1        0                   0                 0
25         0        0         1        0                   0                 0
26         0        0         1        0                   0                 0
27         0        1         0        0                   0                 0
28         0        1         0        0                   0                 0
29         0        1         0        0                   0                 0
...      ...      ...       ...      ...                 ...               ...
7322       0        0         0        0                   0                 1
7323       0        0         0        0                   0                 1
7324       0        0         0        0                   0                 1
7325       0        0         0        0                   0                 1
7326       0        0         0        0                   0                 1
7327       0        0         0        0                   0                 1
7328       0        0         0        0                   0                 1
7329       0        0         0        0                   0                 1
7330       0        0         0        0                   0                 1
7331       0        0         0        0                   0                 1
7332       0        0         0        0                   0                 1
7333       0        0         0        0                   0                 1
7334       0        0         0        0                   0                 1
7335       0        0         0        0                   0                 1
7336       0        0         0        0                   0                 1
7337       0        0         0        0                   0                 1
7338       0        0         0        0                   0                 1
7339       0        0         0        0                   0                 1
7340       0        0         0        0                

In [24]:
X_train.shape


(5146, 562)

In [25]:
y_train.shape

(2206, 562)

In [31]:
df=pd.DataFrame(X_train)

In [26]:
X_train.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
count        5146.000000        5146.000000        5146.000000   
mean            0.273771          -0.017863          -0.108360   
std             0.072658           0.042764           0.057393   
min            -1.000000          -1.000000          -1.000000   
25%             0.263492          -0.024907          -0.120543   
50%             0.277194          -0.017226          -0.108518   
75%             0.288240          -0.010991          -0.097590   
max             0.692761           1.000000           1.000000   

       tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
count       5146.000000       5146.000000       5146.000000       5146.000000   
mean          -0.610448         -0.517362         -0.608361         -0.635275   
std            0.447265          0.500266          0.418460          0.422315   
min           -1.000000         -0.999873         -1.000000         -1.000000   
25%           -0.992825         -0.978014         -0.980681         -0.993620   
50%           -0.949849         -0.865524         -0.867543         -0.954088   
75%           -0.245146         -0.042122         -0.264772         -0.297145   
max            0.899922          0.873037          1.000000          0.950758   

       tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X     ...       \
count       5146.000000       5146.000000       5146.000000     ...        
mean          -0.533025         -0.609823         -0.475097     ...        
std            0.483615          0.414040          0.543542     ...        
min           -1.000000         -0.999963         -1.000000     ...        
25%           -0.978047         -0.980634         -0.936302     ...        
50%           -0.871746         -0.865277         -0.888751     ...        
75%           -0.073639         -0.267938         -0.024359     ...        
max            0.967664          1.000000          0.907994     ...        

       fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
count                      5146.000000                      5146.000000   
mean                         -0.305114                        -0.622591   
std                           0.322544                         0.309758   
min                          -0.995357                        -0.999595   
25%                          -0.541728                        -0.845021   
50%                          -0.341580                        -0.709158   
75%                          -0.120358                        -0.499790   
max                           0.989538                         0.956845   

       angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
count                  5146.000000                           5146.000000   
mean                      0.007369                              0.000323   
std                       0.332395                              0.446879   
min                      -0.976580                             -1.000000   
25%                      -0.121955                             -0.287197   
50%                       0.008978                              0.006074   
75%                       0.147620                              0.287308   
max                       1.000000                              0.991899   

       angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
count                       5146.000000                           5146.000000   
mean                           0.012293                             -0.008529   
std                            0.604082                              0.477129   
min                           -0.999218                             -1.000000   
25%                           -0.476891                             -0.381043   
50%                            0.014450                             -0.003134   
75%                            0.502013                              

In [54]:
X_train= test1.iloc[:,:-1].values
y_train= test1.iloc[:, -1].values


In [55]:
X_test= test1.iloc[:,:-1].values
y_test= test1.iloc[:, -1].values


In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [52]:
from skmultilearn.adapt import MLkNN

classifier = MLkNN(k=20)

In [65]:
y_pred = classifier.predict(X_test)



In [66]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,f1_score
cm = confusion_matrix(y_test, y_pred)
accuracy_score=accuracy_score(y_test,y_pred)
recall_score=recall_score(y_test,y_pred,average='weighted')
f1_score=f1_score(y_test,y_pred,average='weighted')
print(y_pred)
print(cm)
print(accuracy_score)
print(recall_score)
print(f1_score)

['STANDING' 'STANDING' 'STANDING' ... 'WALKING_UPSTAIRS'
 'WALKING_UPSTAIRS' 'WALKING_UPSTAIRS']
[[1407    0    0    0    0    0]
 [   0 1266   20    0    0    0]
 [   0   21 1353    0    0    0]
 [   0    0    0 1226    0    0]
 [   0    0    0    0  986    0]
 [   0    0    0    0    0 1073]]
0.9944232861806311
0.9944232861806311
0.9944233548240909


In [67]:
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 

In [68]:
accuracy = svm_model_linear.score(X_test, y_test) 

In [69]:
cm = confusion_matrix(y_test, svm_predictions) 


In [70]:
print(accuracy)
print(cm)

0.9968715995647442
[[1407    0    0    0    0    0]
 [   0 1278    8    0    0    0]
 [   0   15 1359    0    0    0]
 [   0    0    0 1226    0    0]
 [   0    0    0    0  986    0]
 [   0    0    0    0    0 1073]]


In [71]:
test2=pd.read_csv('test.csv')

In [72]:
test2.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
count        2947.000000        2947.000000        2947.000000   
mean            0.273996          -0.017863          -0.108386   
std             0.060570           0.025745           0.042747   
min            -0.592004          -0.362884          -0.576184   
25%             0.262075          -0.024961          -0.121162   
50%             0.277113          -0.016967          -0.108458   
75%             0.288097          -0.010143          -0.097123   
max             0.671887           0.246106           0.494114   

       tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
count       2947.000000       2947.000000       2947.000000       2947.000000   
mean          -0.613635         -0.508330         -0.633797         -0.641278   
std            0.412597          0.494269          0.362699          0.385199   
min           -0.999606         -1.000000         -0.998955         -0.999417   
25%           -0.990914         -0.973664         -0.976122         -0.992333   
50%           -0.931214         -0.790972         -0.827534         -0.937664   
75%           -0.267395         -0.105919         -0.311432         -0.321719   
max            0.465299          1.000000          0.489703          0.439657   

       tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X     ...       \
count       2947.000000       2947.000000       2947.000000     ...        
mean          -0.522676         -0.637038         -0.462063     ...        
std            0.479899          0.357753          0.523916     ...        
min           -0.999914         -0.998899         -0.952357     ...        
25%           -0.974131         -0.975352         -0.934447     ...        
50%           -0.799907         -0.817005         -0.852659     ...        
75%           -0.133488         -0.322771         -0.009965     ...        
max            1.000000          0.427958          0.786436     ...        

       fBodyBodyGyroJerkMag-skewness()  fBodyBodyGyroJerkMag-kurtosis()  \
count                      2947.000000                      2947.000000   
mean                         -0.277593                        -0.598756   
std                           0.317245                         0.311042   
min                          -1.000000                        -1.000000   
25%                          -0.517494                        -0.829593   
50%                          -0.311023                        -0.683672   
75%                          -0.083559                        -0.458332   
max                           1.000000                         1.000000   

       angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
count                  2947.000000                           2947.000000   
mean                      0.005264                              0.003799   
std                       0.336147                              0.445077   
min                      -1.000000                             -0.993402   
25%                      -0.130541                             -0.282600   
50%                       0.005188                              0.006767   
75%                       0.146200                              0.288113   
max                       0.998898                              0.986347   

       angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
count                       2947.000000                           2947.000000   
mean                           0.040029                             -0.017298   
std                            0.634989                              0.501311   
min                           -0.998898                             -0.991096   
25%                           -0.518924                             -0.428375   
50%                            0.047113                             -0.026726   
75%                            0.622151                              

In [78]:
X_train1= test2.iloc[:,:-1].values

In [79]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train1 = sc.fit_transform(X_train1)


In [80]:
y_pred = classifier.predict(X_train)

In [81]:
test3=pd.DataFrame(y_pred)

In [83]:
test3.shape

(7352, 1)

In [85]:
 test3.to_csv("test3.csv", index=False)